{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/NordicDFU\/documentation\/NordicDFU","doc:\/\/NordicDFU\/documentation\/NordicDFU\/DFUError"]]},"variants":[{"paths":["\/documentation\/nordicdfu\/dfuerror\/crcerror"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"crcError","kind":"identifier"}],"languages":["swift"]}]}],"metadata":{"role":"symbol","roleHeading":"Case","title":"DFUError.crcError","modules":[{"name":"NordicDFU"}],"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"crcError"}],"externalID":"c:@M@NordicDFU@E@DFUError@DFUErrorCrcError"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/NordicDFU\/documentation\/NordicDFU\/DFUError\/crcError"},"sections":[],"abstract":[{"type":"text","text":"Error raised when the CRC reported by the remote device does not match."},{"text":" ","type":"text"},{"text":"Service has done 3 attempts to send the data.","type":"text"}],"references":{"doc://NordicDFU/documentation/NordicDFU/DFUError":{"navigatorTitle":[{"text":"DFUError","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/NordicDFU\/documentation\/NordicDFU\/DFUError","role":"symbol","url":"\/documentation\/nordicdfu\/dfuerror","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"DFUError","kind":"identifier"}],"abstract":[{"text":"A DFU error enumeration.","type":"text"}],"title":"DFUError","kind":"symbol"},"doc://NordicDFU/documentation/NordicDFU":{"url":"\/documentation\/nordicdfu","title":"NordicDFU","role":"collection","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/NordicDFU\/documentation\/NordicDFU"},"doc://NordicDFU/documentation/NordicDFU/DFUError/crcError":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"crcError","kind":"identifier"}],"kind":"symbol","title":"DFUError.crcError","abstract":[{"text":"Error raised when the CRC reported by the remote device does not match.","type":"text"},{"type":"text","text":" "},{"text":"Service has done 3 attempts to send the data.","type":"text"}],"url":"\/documentation\/nordicdfu\/dfuerror\/crcerror","identifier":"doc:\/\/NordicDFU\/documentation\/NordicDFU\/DFUError\/crcError","type":"topic","role":"symbol"}}}